initial commit
cloudposse/terraform-aws-iam-chamber-user pull request #1
Opened 2018-04-20 19:38 UTC by sarkis

2018-04-20 22:03 UTC, sarkis commented
```
Terraform will perform the following actions:

  + module.chamber_iam_user.module.chamber_user.aws_iam_access_key.default
      id:                  <computed>
      encrypted_secret:    <computed>
      key_fingerprint:     <computed>
      secret:              <computed>
      ses_smtp_password:   <computed>
      status:              <computed>
      user:                "ps-dev-chamber"

  + module.chamber_iam_user.module.chamber_user.aws_iam_user.default
      id:                  <computed>
      arn:                 <computed>
      force_destroy:       "false"
      name:                "ps-dev-chamber"
      path:                "/"
      unique_id:           <computed>

  + module.chamber_iam_user.module.chamber_user.aws_iam_user_policy.default
      id:                  <computed>
      name:                "ps-dev-chamber"
      policy:              "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Sid\": \"\",\n      \"Effect\": \"Allow\",\n      \"Action\": [\n        \"ssm:GetParameters\",\n        \"ssm:DescribeParameters\"\n      ],\n      \"Resource\": \"*\"\n    },\n    {\n      \"Sid\": \"\",\n      \"Effect\": \"Allow\",\n      \"Action\": \"kms:Decrypt\",\n      \"Resource\": \"arn:aws:kms:us-west-2:010570371725:key/365b6e64-5c29-4460-bdf2-6b857d5e71f0\"\n    }\n  ]\n}"
      user:                "ps-dev-chamber"

  + module.chamber_iam_user.module.label.null_resource.default
      id:                  <computed>
      triggers.%:          "5"
      triggers.attributes: ""
      triggers.id:         "ps-dev-chamber"
      triggers.name:       "chamber"
      triggers.namespace:  "ps"
      triggers.stage:      "dev"

  + module.chamber_iam_user.module.chamber_user.module.label.null_resource.default
      id:                  <computed>
      triggers.%:          "5"
      triggers.attributes: ""
      triggers.id:         "ps-dev-chamber"
      triggers.name:       "chamber"
      triggers.namespace:  "ps"
      triggers.stage:      "dev"


Plan: 5 to add, 0 to change, 0 to destroy.
```

2018-04-20 22:12 UTC, osterman requested changes

2018-04-20 22:12 UTC, osterman commented on LICENSE
> +   Copyright 2017-2018 Cloud Posse, LLC
Fix years

2018-04-20 22:12 UTC, osterman commented on variables.tf
> +  default     = "${data.aws_iam_policy_document.default.json}"
Interpolations are not valid as defaults

2018-04-20 22:12 UTC, osterman commented on .travis.yml
> +  - make terraform:install
replace `:` with `/`

2018-04-20 22:12 UTC, osterman commented on README.md
> +Terraform Module to provision a basic IAM system user with access to SSM parameters, suitable for CI/CD Systems
`s/system/chamber/`

2018-04-20 22:12 UTC, osterman commented on README.md
> +Terraform Module to provision a basic IAM system user with access to SSM parameters, suitable for CI/CD Systems
Link chamber to https://github.com/segmentio/chamber

2018-04-20 22:12 UTC, osterman commented on README.md
> +  stage      = "circleci"
let's rename to `staging`

2018-04-20 22:12 UTC, osterman commented on README.md
> +  stage       = "circleci"
lets rename to `staging`

2018-04-20 22:12 UTC, osterman commented on README.md
> +  [andriy_web]: https://github.com/aknysh/
You can add yourself

2018-04-20 22:13 UTC, osterman commented on README.md
> +### Simple usage
We don't need 2 usages for this module. Only a single one.

2018-04-20 22:13 UTC, osterman commented on README.md
> +  kms_key_arn = ""
Add a mock kms key

2018-04-20 22:22 UTC, osterman commented on main.tf
> +  stage     = "${var.stage}"
missing attributes

2018-04-20 22:23 UTC, osterman commented on main.tf
> +    resources = ["*"]
move this to a variable `ssm_resources` with a default value of `["*"]`

2018-04-20 22:23 UTC, osterman commented on main.tf
> +    actions = [
Move this to a variable named `ssm_actions` with a default value of what you have here.

2018-04-20 22:24 UTC, osterman commented on .travis.yml
> +  - make terraform:install
...for all targets

2018-04-20 22:25 UTC, sarkis commented on .travis.yml
> +  - make terraform:install
:+1:

2018-04-20 23:04 UTC, osterman commented on README.md
> +  name       = "chamber"
this will definitely need the `kms_key_arn`

2018-04-20 23:04 UTC, osterman commented on README.md
> +| `kms_key_arn`   |   ``    | KMS key_arn used if Secure Strings are stored in Parameter Store to decrypt secrets.        |    No    |
This should be required

2018-04-20 23:05 UTC, osterman commented on variables.tf
> +variable "name" {}
Use the same variables we have in all of our other modules.

2018-04-20 23:05 UTC, osterman commented on variables.tf
> +variable "name" {}
https://github.com/cloudposse/terraform-aws-key-pair/blob/master/variables.tf#L1-L32

They are all well documented

2018-04-20 23:06 UTC, osterman commented on variables.tf
> +variable "ssm_actions" {
Add `description` to all variables.

2018-04-21 00:15 UTC, osterman commented on README.md
> +  name       = "chamber"
Please add mock `kms_key_arn`

2018-04-21 00:16 UTC, osterman commented on README.md
> +  kms_key_arn = "arn:aws:kms:region:account-id:key/CMK"
Add a realistic arn. It's hard to know what is a placeholder vs what is replaced.

2018-04-21 00:21 UTC, osterman approved these changes

2018-04-21 00:28 UTC, merged